### ISSUE TITLE
Comunity visualization is down

### ISSUE THREAD

**Issue by dinigo** [mwhitaker/time_series_annotation#3]
Hello @mwhitaker ,

I just added the community visualization as described in the README, but it shows the following

![image](https://user-images.githubusercontent.com/3038962/77011959-464ca000-696d-11ea-8053-8001666c6a8b.png)

Which translates to:
> Disabled Community Visualizations
> The owner of this datasource disabled community visualizations

Can you give some context why you removed it? maybe someone else can host it in their GCS?

**Comment by mwhitaker** [comment]
Hi there,

This is a setting that you have to enable. See  [Enable community visualizations in your data source](https://support.google.com/datastudio/answer/9206527?hl=en)

![enable_community_viz](https://user-images.githubusercontent.com/3980239/77014428-74ab8a80-692f-11ea-832c-3be9988a588c.png)

**Comment by dinigo** [comment]
That was it!, thanks
